import { test, type TestContext } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import React, { act } from 'react';
import { createRoot } from 'react-dom/client';
import { JSDOM } from 'jsdom';
import { SlotCore } from '@deepseek-ai/dsh-client-ui-slots';
import type { LocaleRuntime } from '@deepseek-ai/dsh-client-locale/client';
import { AmojiLocaleProvider, chinese, dictionaries, useText, message } from '../src/dsh/i18n.js';
import { english } from '../src/dsh/i18n-dictionary.js';
import { DraftEditor, discardEditor } from '../src/dsh/draft-editor.js';
import { apply, createComponents, type ClientPort } from '../src/dsh/client.js';
import { Manager } from '../src/dsh/manager.js';
import { Conflict } from '../src/dsh/ui.js';
import type { Draft } from '../src/drafts.js';
import type { DshRpc } from '../src/dsh/contracts.js';

const require=createRequire(import.meta.url);
// Execute the published native locale factory. Its settings-row UI dependencies
// are unused here; the LocaleRuntime and dictionary/fallback logic are real.
let localeModule: {LocaleRuntime: typeof LocaleRuntime};
new Function('window',readFileSync(require.resolve('@deepseek-ai/dsh-client-locale/client'),'utf8'))({__ModuleLoader__:{load(value:{factory:(r:(name:string)=>unknown)=>typeof localeModule}){localeModule=value.factory(name=>name.startsWith('react')?require(name):{});}}});
function localeFixture(){
 const locale=new localeModule.LocaleRuntime({emit(){}} as never);
 locale.setLocale('zh');
 locale.register('amoji',{zh:{...chinese,...dictionaries.zh} as Record<keyof typeof english,string>,en:{...english,...dictionaries.en}});
 return locale;
}
async function fixture(t:TestContext){
 const dom=new JSDOM('<div id="root"></div>');const previous={window:globalThis.window,document:globalThis.document};
 Object.assign(globalThis,{window:dom.window,document:dom.window.document,IS_REACT_ACT_ENVIRONMENT:true});
 const root=createRoot(dom.window.document.getElementById('root')!);const locale=localeFixture();
 t.after(async()=>{await act(()=>root.unmount());Object.assign(globalThis,previous);dom.window.close();});
 const render=async(node:React.ReactNode)=>act(async()=>{root.render(React.createElement(AmojiLocaleProvider,{locale,children:node}));});
 const button=(name:string)=>[...dom.window.document.querySelectorAll('button')].find(b=>b.textContent===name||b.getAttribute('aria-label')===name)!;
 return {dom,root,locale,render,button};
}
const fields={name:'用户原名',semantics:{locale:'zh-CN',meaning:'用户固定含义',fallback:'固定文字',tone:'温暖',use_when:['用户场景'],avoid_when:['用户边界']},rights:{license:'CC0'},tags:['原标签']};
test('原生locale热切换更新字段、aria、状态和AI说明，同时保留未保存输入和固定语义',async t=>{
 const f=await fixture(t);const initial={draft_id:'locale-draft',version:1,fields,mode:'create'} as Draft;t.after(()=>discardEditor(initial.draft_id));
 const rpc={management:async(_s:string,method:string)=>{if(method==='listSuggestionModels')return {models:[{provider:'test',model:'model',name:'原模型名'}],current:{provider:'test',model:'model'}};if(method==='suggestAiText')return {fields,notice:'服务器中文说明'};throw new Error(method);}} as unknown as DshRpc;
 await f.render(React.createElement(DraftEditor,{rpc,sessionId:'s',initial,onCreated(){}}));
 const name=f.dom.window.document.querySelector<HTMLInputElement>('input[aria-label="名称"]')!;
 const intent=f.dom.window.document.querySelector<HTMLTextAreaElement>('textarea[aria-label="文字意图"]')!;
 await act(()=>{name.value='未保存名称';name.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));intent.value='用户自己的文字意图';intent.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));});
 await act(()=>f.locale.setLocale('en'));
 assert.equal(f.dom.window.document.querySelector('input[aria-label="Name"]'),name);
 assert.equal(name.value,'未保存名称');assert.equal(intent.value,'用户自己的文字意图');
 assert.ok(f.dom.window.document.querySelector('textarea[aria-label="Fixed meaning"]'));
 assert.ok(f.dom.window.document.querySelector('textarea[aria-label="Use when (one per line)"]'));
 assert.match(f.dom.window.document.body.textContent!,/Unsaved changes/);
 assert.match(f.dom.window.document.body.textContent!,/用户固定含义/);
 assert.match(intent.placeholder,/Tell AI who is speaking/);
 await act(async()=>f.button('Generate wording with AI').click());
 assert.match(f.dom.window.document.body.textContent!,/Wording generated by 原模型名 \(test \/ model\); no image was read/);
 assert.match(f.dom.window.document.body.textContent!,/用户固定含义/);
 await act(()=>f.locale.setLocale('zh'));
 assert.equal(name.getAttribute('aria-label'),'名称');assert.equal(name.value,'未保存名称');
 assert.match(f.dom.window.document.body.textContent!,/由 原模型名（test \/ model）生成文字建议/);
});
test('英文管理页、选择器和动态状态完整显示，GitHub入口可访问，切换保留搜索',async t=>{
 const f=await fixture(t);const rpc={catalog:async()=>[],search:async()=>[],management:async(_s:string,method:string)=>method==='getSettings'?{version:1,style:'neutral',frequency:'restrained',paused:false,appearance:'classic'}:[]} as unknown as DshRpc;
 const Picker=createComponents(rpc).Picker;
 await f.render(React.createElement(React.Fragment,null,React.createElement(Picker,{sessionId:'s'}),React.createElement(Manager,{rpc,sessionId:'s',currentSessionId:'s',open:true,onClose(){},onChanged(){}})));
 await act(async()=>f.button('表情').click());await act(()=>f.locale.setLocale('en'));
 assert.ok(f.dom.window.document.querySelector('[aria-label="Amoji expression picker"]'));
 assert.ok(f.dom.window.document.querySelector('a[aria-label="View Amoji on GitHub"][href="https://github.com/5101good/amoji"]'));
 assert.match(f.dom.window.document.body.textContent!,/0 expressions available/);
 assert.ok(f.button('Create and drafts'));assert.ok(f.button('Save preferences'));
 const input=f.dom.window.document.querySelector<HTMLInputElement>('input[aria-label="Search expressions"]')!;
 await act(()=>{input.value='原搜索词';input.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));});
 await act(()=>f.locale.setLocale('zh'));assert.equal(input.value,'原搜索词');assert.equal(input.getAttribute('aria-label'),'搜索表情');
});
test('错误按稳定code翻译并保留诊断原文，已生成的动态状态随locale更新',async t=>{
 const f=await fixture(t);
 function Status(){const translate=useText();const [status]=React.useState(()=>message('找到 {count} 个候选。',{count:3}));return React.createElement('p',{},translate(status));}
 await f.render(React.createElement(React.Fragment,null,React.createElement(Status),React.createElement(Conflict,{error:Object.assign(new Error('服务端具体诊断'),{code:'SUGGESTION_TIMEOUT'})})));
 assert.match(f.dom.window.document.body.textContent!,/服务端具体诊断/);
 await act(()=>f.locale.setLocale('en'));assert.match(f.dom.window.document.body.textContent!,/Found 3 matches/);assert.match(f.dom.window.document.body.textContent!,/AI generation timed out/);assert.match(f.dom.window.document.body.textContent!,/服务端具体诊断/);
});
test('apply注册原生amoji词典和locale seats，宿主user renderer保持原chat词典，卸载释放字典',()=>{
 const locale=new localeModule.LocaleRuntime({emit(){}} as never);locale.setLocale('en');
 const core=new SlotCore();core.register({name:'root',children:{'conversation.input.left':{kind:'list',scope:'session'},'conversation.chat.node':{kind:'keyed',scope:'session'},'tool.call.toolview':{kind:'keyed',scope:'session'}}} as never,()=>null);
 const original=()=>null;core.register({name:'conversation.chat.node',key:'user',locale:'chat'} as never,original);
 const cleanup:Array<()=>void>=[];
 apply({locale,slots:{register:core.register.bind(core),entries:core.entries.bind(core),subscribe:core.subscribe.bind(core),inject:(_name:string,fn:()=>()=>void)=>fn()},effect(fn:()=>()=>void){cleanup.push(fn());},connection:{rpc:{call:async()=>({ok:true,value:[]})}}} as unknown as ClientPort);
 assert.equal(core.entriesOfSlot('conversation.input.left')[0]!.locale,'amoji');assert.equal(core.entriesOfSlot('conversation.chat.node').find(e=>e.options.key==='user')!.locale,'chat');
 assert.equal(locale.bind('amoji')('表情'),'Expressions');assert.equal(locale.getLocale().active,'en');
 cleanup.forEach(fn=>fn());assert.equal(locale.bind('amoji')('表情'),'表情');assert.equal(core.entriesOfSlot('conversation.chat.node')[0]!.component,original);
});
