import {test} from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {JSDOM} from 'jsdom';
import {createRoot} from 'react-dom/client';
import {DraftEditor} from '../src/dsh/draft-editor.js';
import {Preferences} from '../src/dsh/preferences.js';
import {AiExpressions,aiExpressionDefinition} from '../src/dsh/ai-messages.js';
import {SlotCore} from '@deepseek-ai/dsh-client-ui-slots';
import {SampleCatalog} from '../src/sample-catalog.js';
import {visualMeta} from '../src/dsh/host.js';
import type {Draft} from '../src/drafts.js';
async function domFixture(t:any){const dom=new JSDOM('<div id="root"></div>');const old={window:globalThis.window,document:globalThis.document,FileReader:globalThis.FileReader};Object.assign(globalThis,{window:dom.window,document:dom.window.document,FileReader:dom.window.FileReader,IS_REACT_ACT_ENVIRONMENT:true});const root=createRoot(dom.window.document.getElementById('root')!);t.after(async()=>{await React.act(()=>root.unmount());Object.assign(globalThis,old);dom.window.close();});return{dom,root,button:(text:string)=>[...dom.window.document.querySelectorAll('button')].find(b=>b.textContent===text)!};}
const e=(await SampleCatalog.load(new URL('../assets/samples/',import.meta.url))).all()[0]!;
const draft:Draft={draft_id:'d',version:1,updated_at:'now',fields:{name:e.name,semantics:e.semantics,rights:e.rights},visual:e.visual};
test('草稿实际操作必须load和明确勾选；输入修改使预览失效',async t=>{const f=await domFixture(t);let confirms=0;const rpc:any={management:async(_s:string,method:string,args:any)=>{if(method==='saveDraft')return{...draft,version:2,fields:args.fields};if(method==='previewDraft')return{draft:{...draft,version:2},primary:'data:image/png;base64,AAAA',poster:null};if(method==='confirmDraft'){confirms++;return e;}}};await React.act(()=>f.root.render(React.createElement(DraftEditor,{rpc,sessionId:'s',initial:draft,onCreated:()=>{}})));await React.act(async()=>f.button('保存并预览').click());assert.equal(f.button('确认加入表情库').disabled,true);const checkbox=f.dom.window.document.querySelector<HTMLInputElement>('input[type=checkbox]')!;assert.equal(checkbox.disabled,true);await React.act(()=>f.dom.window.document.querySelector('[aria-label="图文确认预览"] img')!.dispatchEvent(new f.dom.window.Event('load')));assert.equal(f.button('确认加入表情库').disabled,true);await React.act(()=>checkbox.click());assert.equal(f.button('确认加入表情库').disabled,false);const name=f.dom.window.document.querySelector<HTMLInputElement>('[aria-label="名称"]')!;await React.act(()=>{Object.getOwnPropertyDescriptor(f.dom.window.HTMLInputElement.prototype,'value')!.set!.call(name,'新含义');name.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));});assert.equal(f.dom.window.document.querySelector('[aria-label="图文确认预览"]'),null);assert.equal(confirms,0);await React.act(async()=>f.button('保存并预览').click());await React.act(()=>f.dom.window.document.querySelector('[aria-label="图文确认预览"] img')!.dispatchEvent(new f.dom.window.Event('load')));await React.act(()=>f.dom.window.document.querySelector<HTMLInputElement>('input[type=checkbox]')!.click());await React.act(async()=>f.button('确认加入表情库').click());assert.equal(confirms,1);});
test('偏好CAS冲突保留本次输入并显式接纳最新版本',async t=>{const f=await domFixture(t);let args:any;const rpc:any={management:async(_s:string,m:string,a:any)=>{if(m==='getSettings')return{version:1,style:'neutral',frequency:'restrained',paused:false};args=a;throw Object.assign(new Error('SETTINGS_CONFLICT'),{current:{version:2,style:'warm',frequency:'active',paused:false}});}};await React.act(async()=>f.root.render(React.createElement(Preferences,{rpc,sessionId:'s'})));const select=f.dom.window.document.querySelector<HTMLSelectElement>('[aria-label="风格"]')!;await React.act(()=>{select.value='playful';select.dispatchEvent(new f.dom.window.Event('change',{bubbles:true}));});await React.act(async()=>f.button('保存偏好').click());assert.equal(select.value,'playful');assert.equal(args.version,1);assert.match(f.dom.window.document.body.textContent!,/本次输入已保留/);await React.act(()=>f.button('保留本次输入，继续编辑').click());await React.act(async()=>f.button('保存偏好').click());assert.equal(args.version,2);assert.equal(args.preferences.style,'playful');});
test('折叠工具组后独立节点直接显示去重AI图，无最终文字也不占用tail扩展',async t=>{const f=await domFixture(t);const meta=visualMeta({message_id:'ai',revision:e} as any);const rpc:any={visual:async()=>({expression:e,primary:'data:image/png;base64,AAAA',poster:null}),display:async()=>{}};const match=(event:any)=>({event,role:'update',location:{kind:'turn',turn:{turn:1}}});const result={type:'tool/result',surfaceOp:'append',seq:5,data:{turn:1,meta,message:{content:[{isError:false}]}}};const context:any={key:'amoji:1',id:'1',matches:[match(result),match({...result,seq:6}),match({type:'turn/end',seq:9,data:{turn:1}})]};const node:any=aiExpressionDefinition.buildViewNode!(context);assert.equal(node.anchorSeq,9);assert.equal(node.visibility,'visible');assert.equal(node.data.length,1);assert.ok(node.anchorSeq>5,'位于已折叠过程之后');await React.act(async()=>f.root.render(React.createElement(React.Fragment,{},React.createElement('span',{},'其他插件与宿主操作'),React.createElement(AiExpressions,{rpc,sessionId:'s',node}))));assert.equal(f.dom.window.document.querySelectorAll('[aria-label="AI 表情"] img').length,1);assert.match(f.dom.window.document.body.textContent!,/其他插件与宿主操作/);assert.equal(aiExpressionDefinition.match({type:'user/message',data:{}} as any),null);});

test('建议请求期间修改意图拒绝迟到候选；采用前可独立编辑',async t=>{const f=await domFixture(t);let resolve:(value:any)=>void=()=>{};const rpc:any={management:async(_s:string,m:string)=>m==='listSuggestionModels'?{models:[{provider:'p',model:'flash',name:'Flash'}],current:{provider:'p',model:'flash'}}:new Promise(r=>{resolve=r;})};await React.act(()=>f.root.render(React.createElement(DraftEditor,{rpc,sessionId:'s',initial:{...draft,draft_id:'suggest'},onCreated:()=>{}})));await React.act(async()=>{});const input=f.dom.window.document.querySelector<HTMLTextAreaElement>('[aria-label="文字意图"]')!;const fill=async(value:string)=>React.act(()=>{input.value=value;input.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));});await fill('感谢');await React.act(()=>f.button('AI 生成文字建议').click());await fill('安慰');await React.act(()=>resolve({fields:{name:'过期建议',semantics:e.semantics},notice:'旧结果'}));assert.equal(!!f.dom.window.document.querySelector('[aria-label="待选建议"]'),false);assert.equal(input.value,'安慰');});
test('完成回合后展开工具组只保留文字反馈，主流图不重复',async t=>{const f=await domFixture(t);const {createComponents}=await import('../src/dsh/client.js');const meta=visualMeta({message_id:'ai',revision:e} as any);const rpc:any={visual:async()=>({expression:e,primary:'data:image/png;base64,AAAA',poster:null}),display:async()=>{}};const Tool=createComponents(rpc).ToolView;const useChat=(selector:any)=>selector({nodes:{values:()=>[{kind:'amoji-expressions',data:[meta]}]}});await React.act(async()=>f.root.render(React.createElement(React.Fragment,{},React.createElement(Tool,{sessionId:'s',block:{kind:'tool-result',meta},useChat}),React.createElement(AiExpressions,{rpc,sessionId:'s',node:{data:[meta]}}))));assert.equal(f.dom.window.document.querySelectorAll('img').length,1);assert.match(f.dom.window.document.body.textContent!,/表情已显示在对话中/);});

test('草稿组件会话卸载重挂保留输入，重新预览才能确认',async t=>{const f=await domFixture(t);const rpc:any={management:async()=>draft};const initial={...draft,draft_id:'retain'};await React.act(()=>f.root.render(React.createElement(DraftEditor,{rpc,sessionId:'a',initial,onCreated:()=>{}})));const name=f.dom.window.document.querySelector<HTMLInputElement>('[aria-label="名称"]')!;await React.act(()=>{name.value='未保存的输入';name.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));});await React.act(()=>f.root.render(React.createElement('p',{},'会话B')));await React.act(()=>f.root.render(React.createElement(DraftEditor,{rpc,sessionId:'a',initial,onCreated:()=>{}})));assert.equal(f.dom.window.document.querySelector<HTMLInputElement>('[aria-label="名称"]')!.value,'未保存的输入');assert.equal(!!f.dom.window.document.querySelector('[aria-label="图文确认预览"]'),false);});
test('包导入结果未知锁定原File并重试相同文件，导出只有完整成功才下载',async t=>{const f=await domFixture(t);const {PackControls}=await import('../src/dsh/pack-controls.js');const files:File[]=[];let imports=0;const rpc:any={importPack:async(_s:string,file:File)=>{files.push(file);if(++imports===1)throw Object.assign(new Error('结果尚待核对'),{code:'PACK_OUTCOME_UNKNOWN'});return{added:1,existing:0};},exportPack:async()=>{throw new Error('素材缺失');}};await React.act(()=>f.root.render(React.createElement(PackControls,{rpc,sessionId:'a',refs:[e],onImported:()=>{}})));const input=f.dom.window.document.querySelector<HTMLInputElement>('[aria-label="导入表情包"]')!;const file=new f.dom.window.File(['zip'],'a.amoji');Object.defineProperty(input,'files',{value:[file]});await React.act(()=>input.dispatchEvent(new f.dom.window.Event('change',{bubbles:true})));await React.act(async()=>f.button('导入完整包').click());assert.equal(input.disabled,true);await React.act(async()=>f.button('重试同一包并核对').click());assert.equal(files[0],files[1]);assert.equal(input.disabled,false);await React.act(async()=>f.button('导出所选 1 个版本').click());assert.match(f.dom.window.document.body.textContent!,/素材缺失/);assert.equal(f.dom.window.document.querySelectorAll('a[download]').length,0);});

test('导出成功保留真实下载入口，不把生成完成冒充下载完成',async t=>{
 const f=await domFixture(t);const {PackControls}=await import('../src/dsh/pack-controls.js');
 const create=URL.createObjectURL,revoke=URL.revokeObjectURL;const revoked:string[]=[];
 URL.createObjectURL=()=> 'blob:qa-export';URL.revokeObjectURL=url=>{revoked.push(url);};t.after(()=>{URL.createObjectURL=create;URL.revokeObjectURL=revoke;});
 await React.act(()=>f.root.render(React.createElement(PackControls,{rpc:{exportPack:async()=>new Blob(['valid-pack'])} as any,sessionId:'a',refs:[e],onImported:()=>{}})));
 await React.act(async()=>f.button('导出所选 1 个版本').click());
 const link=f.dom.window.document.querySelector<HTMLAnchorElement>('a[download]');assert.ok(link,'完成后保留可点击下载入口');assert.equal(link.href,'blob:qa-export');assert.equal(link.download,'我的表情.amoji');
 assert.ok(!f.dom.window.document.body.textContent!.includes('已下载'));
 await React.act(()=>f.root.render(React.createElement('div')));assert.ok(revoked.includes('blob:qa-export'),'卸载释放下载 URL');
});

test('AI语义单输入框带提示，默认当前会话模型，可选其他模型；取消和生成均不自动覆盖草稿',async t=>{
 const f=await domFixture(t);let request:any,requestSignal:AbortSignal|undefined,deliver:(v:any)=>void=()=>{};
 const rpc:any={management:async(_s:string,method:string,args:any,signal?:AbortSignal)=>{
  if(method==='listSuggestionModels')return{models:[{provider:'p',model:'flash',name:'Flash'},{provider:'p',model:'current',name:'Current'}],current:{provider:'p',model:'current'}};
  assert.equal(method,'suggestAiText');request=args;requestSignal=signal;return new Promise(resolve=>{deliver=resolve;});
 }};
 await React.act(()=>f.root.render(React.createElement(DraftEditor,{rpc,sessionId:'s',initial:{...draft,draft_id:'ai-model-selection'},onCreated:()=>{}})));
 const details=f.dom.window.document.querySelector('[aria-label="AI 语义创作"]')!;
 await React.act(async()=>{});
 assert.equal(details.querySelectorAll('textarea').length,1);assert.equal(details.querySelector('[aria-label="补充说明"]'),null);
 const input=details.querySelector('textarea')!;assert.match(input.placeholder,/谁对谁.*情境.*语气/);
 const select=details.querySelector('select')!;assert.equal(select.value,JSON.stringify(['p','current']));
 await React.act(()=>{input.value='AI向用户承认刚才理解错了，真诚但不自责';input.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));select.value=JSON.stringify(['p','flash']);select.dispatchEvent(new f.dom.window.Event('change',{bubbles:true}));});
 await React.act(()=>f.button('AI 生成文字建议').click());assert.equal(request.model,'flash');assert.equal('notes' in request,false);
 await React.act(()=>f.button('取消生成').click());assert.equal(requestSignal?.aborted,true);
 await React.act(()=>deliver({fields:{name:'迟到',semantics:e.semantics,tags:[]},notice:'结果'}));assert.equal(f.dom.window.document.querySelector('[aria-label="待选建议"]'),null);
 await React.act(()=>f.button('AI 生成文字建议').click());await React.act(()=>deliver({fields:{name:'是我理解错了',semantics:{...e.semantics,meaning:'承认刚才理解错误并愿意重新对齐'},tags:['澄清']},notice:'AI生成'}));
 const candidate=f.dom.window.document.querySelector('[aria-label="待选建议"]')!;assert.ok(candidate);
 assert.equal(f.dom.window.document.querySelector<HTMLInputElement>('fieldset > .stack [aria-label="名称"]')!.value,draft.fields.name);
 await React.act(()=>f.button('采用建议').click());assert.equal(f.dom.window.document.querySelector<HTMLInputElement>('[aria-label="名称"]')!.value,'是我理解错了');
 assert.match(f.dom.window.document.body.textContent!,/仍需保存和预览确认/);
});

test('创作以单一意图输入为中心，结果先显示摘要，手动编辑与高级字段按需展开',async t=>{
 const f=await domFixture(t);const empty={...draft,draft_id:'progressive-create',fields:{name:'',semantics:{locale:'zh-CN',meaning:'',fallback:''},rights:{license:'仅供个人使用'}}};
 const rpc:any={management:async()=>({models:[{provider:'p',model:'current',name:'Current'}],current:{provider:'p',model:'current'}})};
 await React.act(async()=>f.root.render(React.createElement(DraftEditor,{rpc,sessionId:'s',initial:empty,onCreated:()=>{}})));
 const composer=f.dom.window.document.querySelector('[aria-label="AI 语义创作"]');assert.ok(composer);assert.equal(composer.querySelectorAll('textarea').length,1);
 const manual=f.dom.window.document.querySelector<HTMLDetailsElement>('[data-editor="manual"]');assert.ok(manual);assert.equal(manual.open,false);assert.match(manual.querySelector('summary')!.textContent!,/手动填写/);
 const actions=f.dom.window.document.querySelector('.amoji-draft-actions');assert.ok(actions?.textContent?.includes('保存并预览'));
 assert.ok(f.dom.window.document.querySelector('.amoji-artwork'));
});
