import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createAmojiServer } from '../src/mcp-server.js';
import { SampleCatalog } from '../src/sample-catalog.js';
import { SampleRuntime } from '../src/sample-runtime.js';

test('真实 MCP 协议返回纯文本候选；伪造模型参数不能改变会话或语义', async t => {
  const catalog = await SampleCatalog.load(new URL('../assets/samples/', import.meta.url));
  const server = createAmojiServer(new SampleRuntime(catalog));
  const client = new Client({ name: 'amoji-contract-test', version: '1' });
  const [serverTransport, clientTransport] = InMemoryTransport.createLinkedPair();
  await server.connect(serverTransport);
  await client.connect(clientTransport);
  t.after(async () => { await client.close(); await server.close(); });
  const _meta = { threadId: 'thread-a', 'x-codex-turn-metadata': { thread_id: 'thread-a', turn_id: 'turn-1' } };
  const result = await client.callTool({ name: 'amoji_search', arguments: { query: '加油' }, _meta });
  assert.equal(result.isError, undefined);
  const content = result.content as Array<{ type: string; text: string }>;
  assert.deepEqual(content.map(c => c.type), ['text']);
  const candidate = JSON.parse(content[0]!.text).candidates[0];
  assert.equal(candidate.visual, undefined);
  const bad = await client.callTool({ name: 'amoji_emit', arguments: { selection_token: candidate.selection_token, meaning: '改写', target_session: 'b' }, _meta });
  assert.equal(bad.isError, true);
  const missing = await client.callTool({ name: 'amoji_search', arguments: { query: '加油' } });
  assert.equal(missing.isError, true);
  const sent = await client.callTool({ name: 'amoji_emit', arguments: { selection_token: candidate.selection_token }, _meta });
  assert.equal(sent.isError, undefined);
  assert.deepEqual((sent.content as Array<{type: string}>).map(c => c.type), ['text']);
});
