import { test } from 'node:test';
import assert from 'node:assert/strict';
import { SampleCatalog } from '../src/sample-catalog.js';
import { SampleRuntime } from '../src/sample-runtime.js';
import { PanelServer } from '../src/panel-server.js';

test('面板点选只完成对应会话的待选请求，其他会话和未授权网页不能代发', async t => {
  const runtime = new SampleRuntime(await SampleCatalog.load(new URL('../assets/samples/', import.meta.url)));
  const opened: string[] = [];
  const panel = await PanelServer.start(runtime, async url => { opened.push(url); }, new URL('../web/', import.meta.url));
  t.after(() => panel.close());
  const a = { host: 'codex' as const, sessionId: 'a', turnId: '1' };
  const b = { ...a, sessionId: 'b' };
  const abortB = new AbortController();
  t.after(() => abortB.abort());
  const first = panel.pick(a, new AbortController().signal);
  const second = panel.pick(b, abortB.signal).catch(error => error as Error);
  const url = new URL(opened[0]!);
  const other = new URL(opened[1]!);
  const headers = { Authorization: `Bearer ${url.hash.slice(1)}`, 'Content-Type': 'application/json' };
  assert.match(await (await fetch(url.origin)).text(), /表情选择器/);
  assert.equal((await fetch(`${url.origin}/api/state`)).status, 401);
  assert.equal((await fetch(`${url.origin}/api/state`, { headers: { ...headers, Origin: 'https://elsewhere.test' } })).status, 403);
  const state = await (await fetch(`${url.origin}/api/state`, { headers })).json();
  const otherState = await (await fetch(`${url.origin}/api/state`, { headers: { Authorization: `Bearer ${other.hash.slice(1)}` } })).json();
  const searchResponse = await fetch(`${url.origin}/api/search?query=${encodeURIComponent('温暖 支持')}&limit=5`, { headers });
  assert.equal(searchResponse.status, 200);
  const searched = await searchResponse.json();
  assert.deepEqual(searched.expressions.map((expression: { name: string }) => expression.name), ['一步一步来']);
  assert.deepEqual((await (await fetch(`${url.origin}/api/search?query=${encodeURIComponent('完全不存在')}`, { headers })).json()).expressions, []);
  assert.equal((await fetch(`${url.origin}/api/search?query=${encodeURIComponent('😀'.repeat(241))}`, { headers })).status, 400);
  assert.equal((await fetch(`${url.origin}/api/search?query=支持&limit=6`, { headers })).status, 400);
  const expression = state.expressions[0];
  const select = (pickId: string) => fetch(`${url.origin}/api/select`, { method: 'POST', headers, body: JSON.stringify({ pick_id: pickId, asset_id: expression.asset_id, revision_id: expression.revision_id }) });
  assert.equal((await select(otherState.pending_pick)).status, 409);
  assert.equal((await select(state.pending_pick)).status, 200);
  const sent = await first;
  assert.equal(sent.revision.revision_id, expression.revision_id);
  const retry = await select(state.pending_pick);
  assert.equal(retry.status, 200);
  assert.equal((await retry.json()).message_id, sent.message_id);
  assert.equal(runtime.messages(a).length, 1);
  assert.equal(runtime.messages(b).length, 0);
  abortB.abort();
  assert.match((await second as Error).message, /取消/);
});

test('已取消请求的浏览器打开延迟失败，不会取消下一次选择', async t => {
  const runtime = new SampleRuntime(await SampleCatalog.load(new URL('../assets/samples/', import.meta.url)));
  let rejectFirst!: (error: Error) => void;
  let count = 0;
  const panel = await PanelServer.start(runtime, () => ++count === 1 ? new Promise((_, reject) => { rejectFirst = reject; }) : Promise.resolve());
  t.after(() => panel.close());
  const context = { host: 'codex' as const, sessionId: 'a', turnId: '1' };
  const abortA = new AbortController();
  const a = panel.pick(context, abortA.signal).catch(() => {});
  abortA.abort(); await a;
  const abortB = new AbortController();
  const b = panel.pick({ ...context, turnId: '2' }, abortB.signal).catch(() => {});
  t.after(() => abortB.abort());
  const url = new URL(panel.url(context));
  const headers = { Authorization: `Bearer ${url.hash.slice(1)}` };
  const before = await (await fetch(`${url.origin}/api/state`, { headers })).json();
  rejectFirst(new Error('late failure'));
  await new Promise(resolve => setImmediate(resolve));
  const after = await (await fetch(`${url.origin}/api/state`, { headers })).json();
  assert.ok(before.pending_pick);
  assert.equal(after.pending_pick, before.pending_pick);
  abortB.abort(); await b;
});
