import React,{useEffect,useRef,useState} from 'react';
import type {Draft,DraftFields} from '../drafts.js';
import type {DshRpc} from './contracts.js';
import type {Expression} from '../sample-catalog.js';
import {Conflict} from './ui.js';
export function Fields({value,onChange}:{value:DraftFields;onChange:(v:DraftFields)=>void}){
 const optional=<T extends object>(value:T,key:keyof T,text:string):T=>{const next={...value};if(text==='')delete next[key];else next[key]=text as T[keyof T];return next;};
 const field=(label:string,key:keyof DraftFields['semantics'],list=false)=><label className={key==='meaning'?'wide':''}>{label}<textarea aria-label={label} value={list?(value.semantics[key] as string[]|undefined)?.join('\n')??'':value.semantics[key] as string??''} onInput={e=>onChange({...value,semantics:key==='tone'?optional(value.semantics,key,e.currentTarget.value):{...value.semantics,[key]:list?(e.currentTarget.value?e.currentTarget.value.split('\n'):[]):e.currentTarget.value}})}/></label>;
 return <div className="fields"><label>名称<input aria-label="名称" value={value.name} onInput={e=>onChange({...value,name:e.currentTarget.value})}/></label><label>语言<input aria-label="语言" value={value.semantics.locale} onInput={e=>onChange({...value,semantics:{...value.semantics,locale:e.currentTarget.value}})}/></label>{field('固定含义','meaning')}{field('文字回退','fallback')}{field('语气','tone')}{field('适用场景（每行一项）','use_when',true)}{field('避免场景（每行一项）','avoid_when',true)}<label>标签（每行一项）<textarea aria-label="标签（每行一项）" value={value.tags?.join('\n')??''} onInput={e=>onChange({...value,tags:e.currentTarget.value?e.currentTarget.value.split('\n'):[]})}/></label>{(['license','creator','source'] as const).map(key=><label key={key}>{{license:'使用许可',creator:'作者',source:'来源'}[key]}<input aria-label={{license:'使用许可',creator:'作者',source:'来源'}[key]} value={value.rights[key]??''} onInput={e=>onChange({...value,rights:key==='license'?{...value.rights,[key]:e.currentTarget.value}:optional(value.rights,key,e.currentTarget.value)})}/></label>)}</div>;
}
const editorCache = new Map<string, {draft:Draft;fields:DraftFields;upload?:string;filename:string;intent:string;notes:string;uncertain:boolean}>();
export function discardEditor(id:string){editorCache.delete(id);}
export function DraftEditor({rpc,sessionId,initial,onCreated,onSaved}:{rpc:DshRpc;sessionId:string;initial:Draft;onCreated:(e:Expression)=>void;onSaved?:(draft:Draft)=>void}){
 const cached=editorCache.get(initial.draft_id);
 const [draft,setDraft]=useState(cached?.draft??initial),[fields,setFields]=useState(cached?.fields??initial.fields),[upload,setUpload]=useState<string|undefined>(cached?.upload),[filename,setFilename]=useState(cached?.filename??''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[status,setStatus]=useState(''),[intent,setIntent]=useState(cached?.intent??''),[notes,setNotes]=useState(cached?.notes??''),[suggesting,setSuggesting]=useState(false),[candidate,setCandidate]=useState<DraftFields>(),[preview,setPreview]=useState<{token:number;draft:Draft;primary:string;poster:string|null}>(),[loaded,setLoaded]=useState(false),[checked,setChecked]=useState(false),[paused,setPaused]=useState(true),[uncertain,setUncertain]=useState(cached?.uncertain??false);
 useEffect(()=>{if(draft.confirmed)editorCache.delete(initial.draft_id);else editorCache.set(initial.draft_id,{draft,fields,upload,filename,intent,notes,uncertain});},[draft,fields,upload,filename,intent,notes,uncertain]);
 const previewEpoch=useRef(0);
 const revokePreview=()=>{previewEpoch.current++;setPreview(undefined);setLoaded(false);setChecked(false);};
 const generation=useRef(0); const currentFields=useRef(fields);currentFields.current=fields;
 const invalidateSuggestion=()=>{generation.current++;setCandidate(undefined);setSuggesting(false);};
 const invalidate=()=>{invalidateSuggestion();revokePreview();};
 const change=(value:DraftFields)=>{invalidate();setFields(value);setStatus('有未保存修改');};
 useEffect(()=>()=>{generation.current++;previewEpoch.current++;},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError(undefined);try{await fn();}catch(e){setError(e);if((e as {code?:string}).code==='DRAFT_OUTCOME_UNKNOWN')setUncertain(true);}finally{setBusy(false);}};
 const save=async()=>{invalidateSuggestion();const result=await rpc.management(sessionId,'saveDraft',{draft_id:draft.draft_id,version:draft.version,fields,...(upload?{upload}:{})});setDraft(result);setUpload(undefined);setUncertain(false);setStatus('草稿已保存');onSaved?.(result);return result;};
 const refresh=()=>void run(async()=>{invalidateSuggestion();const current=await rpc.management(sessionId,'getDraft',{draft_id:draft.draft_id});setError({message:'已读取当前草稿。你的输入仍保留，可继续编辑后重新保存。',current});setDraft(current);setUncertain(false);revokePreview();if(current.confirmed){setStatus('该草稿已确认，返回表情库可查看。');onCreated(await rpc.visual(sessionId,current.confirmed).then(v=>v.expression));}});
 const selectFile=async(file?:File)=>{if(!file)return;invalidate();if(file.size>10*1024*1024){setError(new Error('图片最多 10 MiB，请选择较小文件。'));return;}const token=generation.current;await run(async()=>{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]!);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});if(token!==generation.current)return;setUpload(data);setFilename(file.name);setStatus('素材尚未保存');});};
 return <section className="stack" aria-label="编辑表情草稿"><div><h3>{draft.mode==='edit'?'编辑并创建新版本':draft.mode==='copy'?'创建个人副本':'创建自己的表情'}</h3><small>旧消息保留原图和原义。完成图文预览后由你确认。</small></div>
 <fieldset disabled={busy||uncertain||!!draft.confirmed} className="stack" style={{border:0,padding:0,margin:0}}><label>上传静态图或动图<input aria-label="上传表情图片" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>void selectFile(e.target.files?.[0])}/></label><small>{filename|| (draft.visual?'已保存素材':'PNG / JPEG / WebP / GIF，最多 10 MiB、2048 px；动图最多 10 秒。')}</small>
 <details><summary>从文字意图获取建议</summary><div className="stack"><label>文字意图<textarea aria-label="文字意图" value={intent} onInput={e=>{invalidate();setIntent(e.currentTarget.value);}}/></label><label>补充说明<textarea aria-label="补充说明" value={notes} onInput={e=>{invalidate();setNotes(e.currentTarget.value);}}/></label><button type="button" disabled={suggesting} onClick={()=>{const token=++generation.current;setCandidate(undefined);setSuggesting(true);setError(undefined);void rpc.management(sessionId,'suggestText',{intent,notes}).then(result=>{if(token===generation.current){setCandidate({...result.fields,rights:currentFields.current.rights});setStatus(result.notice);}}).catch(e=>{if(token===generation.current)setError(e);}).finally(()=>{if(token===generation.current)setSuggesting(false);});}}>生成文字建议</button>{candidate&&<section aria-label="待选建议"><h3>待选建议，可独立修改</h3><Fields value={candidate} onChange={setCandidate}/><div className="row"><button type="button" onClick={()=>{change(candidate);setStatus('建议已采用，仍需保存和预览确认');}}>采用建议</button><button type="button" onClick={()=>setCandidate(undefined)}>放弃建议</button></div></section>}</div></details>
 <Fields value={fields} onChange={change}/><div className="row"><button type="button" onClick={()=>void run(async()=>{revokePreview();await save();})}>保存草稿</button><button type="button" onClick={()=>void run(async()=>{revokePreview();const token=previewEpoch.current;const saved=await save();const result=await rpc.management(sessionId,'previewDraft',{draft_id:saved.draft_id,version:saved.version});if(token===previewEpoch.current)setPreview({...result,token});})}>保存并预览</button></div></fieldset>
 {preview&&<section className="preview" aria-label="图文确认预览"><h3>核对图片与固定语义</h3><img key={`${preview.token}:${paused}`} src={paused&&preview.poster?preview.poster:preview.primary} alt={preview.draft.fields.semantics.fallback} onLoad={()=>{if(preview.token===previewEpoch.current)setLoaded(true);}} onError={()=>{if(preview.token!==previewEpoch.current)return;setLoaded(false);setChecked(false);setError(new Error('浏览器无法加载预览，不能确认，请重试预览。'));}}/>{preview.poster&&<button type="button" onClick={()=>{setPaused(!paused);setPreview({...preview,token:++previewEpoch.current});setLoaded(false);setChecked(false);}}>{paused?'播放动图':'暂停动图'}</button>}<strong>{preview.draft.fields.name}</strong><p>{preview.draft.fields.semantics.meaning}</p><details><summary>完整固定语义与许可</summary><pre>{JSON.stringify(preview.draft.fields,null,2)}</pre></details><label><span><input type="checkbox" checked={checked} disabled={!loaded||busy} onChange={e=>{if(preview.token===previewEpoch.current&&loaded)setChecked(e.target.checked);}}/> 我已核对图片和固定语义</span></label><button className="primary" type="button" disabled={!loaded||!checked||busy||uncertain||!!draft.confirmed} onClick={()=>void run(async()=>{if(preview.token!==previewEpoch.current||!loaded||!checked)return;const result=await rpc.management(sessionId,'confirmDraft',{draft_id:draft.draft_id,version:preview.draft.version});setDraft({...draft,confirmed:result});setUncertain(false);setStatus('表情已加入共享库');onCreated(result);})}>确认加入表情库</button></section>}
 <Conflict error={error} onRefresh={refresh}/>{(error as {code?:string})?.code==='ENTRY_CONFLICT'&&(error as {current?:import('../library-management.js').LibraryEntry}).current&&<button type="button" disabled={busy} onClick={()=>void run(async()=>{const entry=(error as {current:import('../library-management.js').LibraryEntry}).current;
 // Transfer the old saved primary bytes through the existing validated upload path.
 // Never inherit the newly current entry's media under a preserve-input action.
 let retained=upload;
 if(!retained){const previous=preview?.draft.draft_id===draft.draft_id&&preview.draft.version===draft.version?preview:await rpc.management(sessionId,'previewDraft',{draft_id:draft.draft_id,version:draft.version});const match=/^data:image\/[a-zA-Z0-9.+-]+;base64,([A-Za-z0-9+/]+={0,2})$/.exec(previous.primary);if(!match)throw new Error('无法迁移原草稿图片，旧草稿和填写已保留，请重试');retained=match[1]!;}
 invalidateSuggestion();const next=await rpc.management(sessionId,'startRevisionDraft',{ref:{asset_id:entry.expression.asset_id,revision_id:entry.expression.revision_id},version:entry.version});setDraft(next);setUpload(retained);revokePreview();setStatus('已从当前版本开始新草稿，本次填写仍保留，请保存并重新预览。');})}>基于当前版本继续，保留本次填写</button>}<p role="status">{busy?'处理中…':status}</p></section>;
}
