import React,{useEffect,useState,useRef} from 'react';
import type {LibraryEntry} from '../library-management.js';
import type {Expression,ExpressionRef} from '../sample-catalog.js';
import type {Draft} from '../drafts.js';
import type {DshRpc} from './contracts.js';
import {AmojiImage,sameRef} from './media.js';
import {Conflict,ExpressionTile,CloseIcon} from './ui.js';
export function LibraryControls({rpc,sessionId,entries,refresh,onDraft,refs,setRefs}:{rpc:DshRpc;sessionId:string;entries:LibraryEntry[];refresh:()=>Promise<void>;onDraft:(d:Draft)=>void;refs:ExpressionRef[];setRefs:(refs:ExpressionRef[])=>void}){
 const inspector=useRef<HTMLElement>(null);
 const [query,setQuery]=useState(''),[archived,setArchived]=useState(false),[entry,setEntry]=useState<LibraryEntry>(),[versions,setVersions]=useState<Expression[]>([]),[selected,setSelected]=useState<Expression>(),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[selectionEpoch,setSelectionEpoch]=useState(0);
 useEffect(()=>{if(selected&&!loading)inspector.current?.querySelector<HTMLButtonElement>('[aria-label="关闭详情"]')?.focus();},[selected,loading]);
 const chooseEntry=(value:LibraryEntry)=>{setEntry(value);setSelectionEpoch(v=>v+1);setSelected(undefined);setVersions([]);setLoading(true);setError(undefined);};
 const manageRpc={...rpc,visual:(_s:string,ref:ExpressionRef)=>rpc.management(sessionId,'revisionVisual',{ref:{asset_id:ref.asset_id,revision_id:ref.revision_id}})};
 const [visualRpc]=useState(()=>manageRpc);
 useEffect(()=>{if(!entry)return;let active=true;setSelected(undefined);setVersions([]);setLoading(true);void rpc.management(sessionId,'listRevisions',{asset_id:entry.expression.asset_id}).then(v=>{if(active){setVersions(v);setSelected(entry.expression);}}).catch(e=>{if(active)setError(e);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[entry?.expression.asset_id,entry?.version,selectionEpoch]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError(undefined);try{await fn();}catch(e){setError(e);}finally{setBusy(false);}};
 const filtered=entries.filter(e=>e.archived===archived&&[e.expression.name,e.expression.semantics.meaning,...(e.expression.tags??[])].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <section className="stack amoji-library"><div className="amoji-library-search"><input aria-label="搜索共享库" placeholder="搜索表情或含义" value={query} onChange={e=>setQuery(e.target.value)}/><div className="row"><button type="button" aria-pressed={!archived} onClick={()=>{setArchived(false);setEntry(undefined);}}>可用</button><button type="button" aria-pressed={archived} onClick={()=>{setArchived(true);setEntry(undefined);}}>已归档</button><button className="quiet" type="button" onClick={()=>void run(refresh)}>刷新库</button></div></div>
 <div className={entry?'amoji-library-layout has-selection':'amoji-library-layout'}><div className="amoji-library-collection"><p className="muted">{filtered.length} 个{archived?'已归档':'可用'}表情</p><div className="amoji-library-grid">{filtered.map(item=><ExpressionTile key={item.expression.asset_id} rpc={visualRpc} sessionId={sessionId} expression={item.expression} selected={entry?.expression.asset_id===item.expression.asset_id} disabled={busy} onSelect={()=>chooseEntry(item)}/>)}</div>{!filtered.length&&<div className="amoji-empty"><p>{query?'没有找到匹配的表情。':archived?'归档的表情会收纳在这里。':'还没有可用表情，去创作或导入一些。'}</p>{query&&<button className="quiet" type="button" onClick={()=>setQuery('')}>清除搜索</button>}</div>}</div>
 <aside ref={inspector} className="amoji-library-inspector" hidden={!entry}>
 {entry&&<div className="amoji-inspector-head"><span className="muted">表情详情</span><button className="icon-button" type="button" aria-label="关闭详情" onClick={()=>{const tile=inspector.current?.parentElement?.querySelector<HTMLButtonElement>('.amoji-expression-tile[aria-pressed=true]');setEntry(undefined);setSelected(undefined);tile?.focus();}}><CloseIcon/></button></div>}
 {loading&&<p role="status">正在读取所选表情的版本…</p>}
 {entry&&selected&&!loading&&selected.asset_id===entry.expression.asset_id&&<section className="stack" aria-label="版本与条目操作"><AmojiImage key={selected.revision_id} rpc={visualRpc} sessionId={sessionId} refValue={selected}/><h3>{selected.name}</h3><small>{{local:'我的表情',builtin:'内置表情',imported:'导入表情'}[entry.origin]} · {entry.archived?'已归档':'可用'}</small><label>固定版本<select aria-label="固定版本" value={selected.revision_id} onChange={e=>setSelected(versions.find(v=>v.revision_id===e.target.value))}>{versions.map((v,i)=><option key={v.revision_id} value={v.revision_id}>{v.name} · {new Date(v.created_at).toLocaleString()} · {v.revision_id.slice(0,8)}{sameRef(v,entry.expression)?'（当前）':''}</option>)}</select></label><p>{selected.semantics.meaning}</p><details><summary>查看完整语义、许可与精确版本</summary><pre>{JSON.stringify(selected,null,2)}</pre></details><div className="row"><button type="button" disabled={busy||entry.archived||!sameRef(selected,entry.expression)} onClick={()=>void run(async()=>onDraft(await rpc.management(sessionId,'startRevisionDraft',{ref:{asset_id:selected.asset_id,revision_id:selected.revision_id},version:entry.version})))}>{entry.origin==='local'?'编辑新版本':'创建个人副本'}</button>{entry.origin!=='local'&&!sameRef(selected,entry.expression)&&<button type="button" disabled={busy} onClick={()=>void run(async()=>{chooseEntry(await rpc.management(sessionId,'selectRevision',{ref:{asset_id:selected.asset_id,revision_id:selected.revision_id},version:entry.version}));await refresh();})}>设为当前版本</button>}<button type="button" disabled={busy} onClick={()=>void run(async()=>{chooseEntry(await rpc.management(sessionId,'setArchived',{asset_id:entry.expression.asset_id,version:entry.version,archived:!entry.archived}));await refresh();})}>{entry.archived?'恢复到可用':'归档表情'}</button><button type="button" aria-pressed={refs.some(r=>sameRef(r,selected))} onClick={()=>setRefs(refs.some(r=>sameRef(r,selected))?refs.filter(r=>!sameRef(r,selected)):[...refs,{asset_id:selected.asset_id,revision_id:selected.revision_id}])}>{refs.some(r=>sameRef(r,selected))?'取消导出选择':'选择此版本导出'}</button></div></section>}
 </aside></div><Conflict error={error}/>{(error as {current?:LibraryEntry})?.current&&<button type="button" onClick={()=>{chooseEntry((error as {current:LibraryEntry}).current);}}>读取当前条目后继续</button>}</section>;
}
