import React,{useEffect,useState} from 'react';
import type {LibraryEntry} from '../library-management.js';
import type {Expression,ExpressionRef} from '../sample-catalog.js';
import type {Draft} from '../drafts.js';
import type {DshRpc} from './contracts.js';
import {AmojiImage,sameRef} from './media.js';
import {Conflict} from './ui.js';
export function LibraryControls({rpc,sessionId,entries,refresh,onDraft,refs,setRefs}:{rpc:DshRpc;sessionId:string;entries:LibraryEntry[];refresh:()=>Promise<void>;onDraft:(d:Draft)=>void;refs:ExpressionRef[];setRefs:(refs:ExpressionRef[])=>void}){
 const [query,setQuery]=useState(''),[archived,setArchived]=useState(false),[entry,setEntry]=useState<LibraryEntry>(),[versions,setVersions]=useState<Expression[]>([]),[selected,setSelected]=useState<Expression>(),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false);
 const manageRpc={...rpc,visual:(_s:string,ref:ExpressionRef)=>rpc.management(sessionId,'revisionVisual',{ref:{asset_id:ref.asset_id,revision_id:ref.revision_id}})};
 const [visualRpc]=useState(()=>manageRpc);
 useEffect(()=>{if(!entry)return;let active=true;void rpc.management(sessionId,'listRevisions',{asset_id:entry.expression.asset_id}).then(v=>{if(active){setVersions(v);setSelected(entry.expression);}}).catch(e=>{if(active)setError(e);});return()=>{active=false;};},[entry?.expression.asset_id,entry?.version]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError(undefined);try{await fn();}catch(e){setError(e);}finally{setBusy(false);}};
 const filtered=entries.filter(e=>e.archived===archived&&[e.expression.name,e.expression.semantics.meaning,...(e.expression.tags??[])].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <section className="stack"><div className="row"><input aria-label="搜索共享库" placeholder="搜索名称、含义或标签" value={query} onChange={e=>setQuery(e.target.value)}/><button type="button" aria-pressed={!archived} onClick={()=>setArchived(false)}>可用</button><button type="button" aria-pressed={archived} onClick={()=>setArchived(true)}>已归档</button><button type="button" onClick={()=>void run(refresh)}>刷新库</button></div><div className="grid">{filtered.map(item=><div className="tile" key={item.expression.asset_id}><AmojiImage rpc={visualRpc} sessionId={sessionId} refValue={item.expression}/><button type="button" disabled={busy} aria-pressed={entry?.expression.asset_id===item.expression.asset_id} onClick={()=>{setEntry(item);setError(undefined);}}>{item.expression.name}</button></div>)}</div>{!filtered.length&&<p>这里还没有表情。</p>}
 {entry&&selected&&<section className="stack" aria-label="版本与条目操作"><h3>{selected.name}</h3><small>{{local:'我的表情',builtin:'内置表情',imported:'导入表情'}[entry.origin]} · {entry.archived?'已归档':'可用'}</small><label>固定版本<select aria-label="固定版本" value={selected.revision_id} onChange={e=>setSelected(versions.find(v=>v.revision_id===e.target.value))}>{versions.map((v,i)=><option key={v.revision_id} value={v.revision_id}>{v.name} · {new Date(v.created_at).toLocaleString()} · {v.revision_id.slice(0,8)}{sameRef(v,entry.expression)?'（当前）':''}</option>)}</select></label><AmojiImage key={selected.revision_id} rpc={visualRpc} sessionId={sessionId} refValue={selected}/><p>{selected.semantics.meaning}</p><details><summary>查看完整语义、许可与精确版本</summary><pre>{JSON.stringify(selected,null,2)}</pre></details><div className="row"><button type="button" disabled={busy||entry.archived||!sameRef(selected,entry.expression)} onClick={()=>void run(async()=>onDraft(await rpc.management(sessionId,'startRevisionDraft',{ref:{asset_id:selected.asset_id,revision_id:selected.revision_id},version:entry.version})))}>{entry.origin==='local'?'编辑新版本':'创建个人副本'}</button>{entry.origin!=='local'&&!sameRef(selected,entry.expression)&&<button type="button" disabled={busy} onClick={()=>void run(async()=>{setEntry(await rpc.management(sessionId,'selectRevision',{ref:{asset_id:selected.asset_id,revision_id:selected.revision_id},version:entry.version}));await refresh();})}>设为当前版本</button>}<button type="button" disabled={busy} onClick={()=>void run(async()=>{setEntry(await rpc.management(sessionId,'setArchived',{asset_id:entry.expression.asset_id,version:entry.version,archived:!entry.archived}));await refresh();})}>{entry.archived?'恢复到可用':'归档表情'}</button><button type="button" aria-pressed={refs.some(r=>sameRef(r,selected))} onClick={()=>setRefs(refs.some(r=>sameRef(r,selected))?refs.filter(r=>!sameRef(r,selected)):[...refs,{asset_id:selected.asset_id,revision_id:selected.revision_id}])}>{refs.some(r=>sameRef(r,selected))?'取消导出选择':'选择此版本导出'}</button></div></section>}
 <Conflict error={error}/>{(error as {current?:LibraryEntry})?.current&&<button type="button" onClick={()=>{setEntry((error as {current:LibraryEntry}).current);setError(undefined);}}>读取当前条目后继续</button>}</section>;
}
