import { useText } from './i18n.js';
import React,{useEffect,useLayoutEffect,useState,useRef} from 'react';
import type {LibraryEntry} from '../library-management.js';
import {expressionAppearance,type Appearance} from '../expression-appearance.js';
import type {Expression,ExpressionRef} from '../sample-catalog.js';
import type {Draft} from '../drafts.js';
import type {DshRpc} from './contracts.js';
import {AmojiImage,sameRef} from './media.js';
import {Conflict,ExpressionTile,CloseIcon} from './ui.js';
export function LibraryControls({rpc,sessionId,entries,refresh,onDraft,refs,setRefs}:{rpc:DshRpc;sessionId:string;entries:LibraryEntry[];refresh:()=>Promise<void>;onDraft:(d:Draft)=>void;refs:ExpressionRef[];setRefs:(refs:ExpressionRef[])=>void}){
 const t=useText();
 const inspector=useRef<HTMLElement>(null);
 const returnFocus=useRef<HTMLButtonElement | null>(null);
 const [query,setQuery]=useState(''),[archived,setArchived]=useState(false),[appearance,setAppearance]=useState<Appearance>('classic'),[entry,setEntry]=useState<LibraryEntry>(),[versions,setVersions]=useState<Expression[]>([]),[selected,setSelected]=useState<Expression>(),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[selectionEpoch,setSelectionEpoch]=useState(0);
 useLayoutEffect(()=>{if(!entry&&returnFocus.current){const tile=returnFocus.current;returnFocus.current=null;if(tile.isConnected)tile.focus();}},[entry]);
 useEffect(()=>{if(selected&&!loading)inspector.current?.querySelector<HTMLButtonElement>('.amoji-inspector-head button')?.focus();},[selected,loading]);
 const chooseEntry=(value:LibraryEntry)=>{setEntry(value);setSelectionEpoch(v=>v+1);setSelected(undefined);setVersions([]);setLoading(true);setError(undefined);};
 const manageRpc={...rpc,visual:(_s:string,ref:ExpressionRef)=>rpc.management(sessionId,'revisionVisual',{ref:{asset_id:ref.asset_id,revision_id:ref.revision_id}})};
 const [visualRpc]=useState(()=>manageRpc);
 useEffect(()=>{if(!entry)return;let active=true;setSelected(undefined);setVersions([]);setLoading(true);void rpc.management(sessionId,'listRevisions',{asset_id:entry.expression.asset_id}).then(v=>{if(active){setVersions(v);setSelected(entry.expression);}}).catch(e=>{if(active)setError(e);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[entry?.expression.asset_id,entry?.version,selectionEpoch]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError(undefined);try{await fn();}catch(e){setError(e);}finally{setBusy(false);}};
 const filtered=entries.filter(e=>e.archived===archived&&(e.origin!=='builtin'||!expressionAppearance(e.expression)||expressionAppearance(e.expression)===appearance)&&[e.expression.name,e.expression.semantics.meaning,...(e.expression.tags??[])].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <section className="stack amoji-library"><div className="row" aria-label={t("内置表情画风")}>{([['classic',t("经典")],['office',t("办公")]] as const).map(([value,label])=><button type="button" key={value} aria-pressed={appearance===value} onClick={()=>{setAppearance(value);setEntry(undefined);}}>{label}</button>)}</div><div className="amoji-library-search"><input aria-label={t("搜索共享库")} placeholder={t("搜索表情或含义")} value={query} onChange={e=>setQuery(e.target.value)}/><div className="row"><button type="button" aria-pressed={!archived} onClick={()=>{setArchived(false);setEntry(undefined);}}>{t("可用")}</button><button type="button" aria-pressed={archived} onClick={()=>{setArchived(true);setEntry(undefined);}}>{t("已归档")}</button><button className="quiet" type="button" onClick={()=>void run(refresh)}>{t("刷新库")}</button></div></div>
 <div className={entry?'amoji-library-layout has-selection':'amoji-library-layout'}><div className="amoji-library-collection"><p className="muted">{t(archived?'已归档表情：{count}':'可用表情：{count}',{count:filtered.length})}</p><div className="amoji-library-grid">{filtered.map(item=><ExpressionTile key={item.expression.asset_id} rpc={visualRpc} sessionId={sessionId} expression={item.expression} selected={entry?.expression.asset_id===item.expression.asset_id} disabled={busy} onSelect={()=>chooseEntry(item)}/>)}</div>{!filtered.length&&<div className="amoji-empty"><p>{query?t("没有找到匹配的表情。"):archived?t("归档的表情会收纳在这里。"):t("还没有可用表情，去创作或导入一些。")}</p>{query&&<button className="quiet" type="button" onClick={()=>setQuery('')}>{t("清除搜索")}</button>}</div>}</div>
 <aside ref={inspector} className="amoji-library-inspector" hidden={!entry}>
 {entry&&<div className="amoji-inspector-head"><span className="muted">{t("表情详情")}</span><button className="icon-button" type="button" aria-label={t("关闭详情")} onClick={()=>{returnFocus.current=inspector.current?.parentElement?.querySelector<HTMLButtonElement>('.amoji-expression-tile[aria-pressed=true]')??null;setEntry(undefined);setSelected(undefined);}}><CloseIcon/></button></div>}
 {loading&&<p role="status">{t("正在读取所选表情的版本…")}</p>}
 {entry&&selected&&!loading&&selected.asset_id===entry.expression.asset_id&&<section className="stack" aria-label={t("版本与条目操作")}><AmojiImage key={selected.revision_id} rpc={visualRpc} sessionId={sessionId} refValue={selected}/><h3>{selected.name}</h3><small>{{local:t("我的表情"),builtin:t("内置表情"),imported:t("导入表情")}[entry.origin]} · {entry.archived?t("已归档"):t("可用")}</small><label>{t("固定版本")}<select aria-label={t("固定版本")} value={selected.revision_id} onChange={e=>setSelected(versions.find(v=>v.revision_id===e.target.value))}>{versions.map((v,i)=><option key={v.revision_id} value={v.revision_id}>{v.name} · {new Date(v.created_at).toLocaleString(t('语言')==='Language'?'en-US':'zh-CN')} · {v.revision_id.slice(0,8)}{sameRef(v,entry.expression)?t("（当前）"):''}</option>)}</select></label><p>{selected.semantics.meaning}</p><details><summary>{t("查看完整语义、许可与精确版本")}</summary><pre>{JSON.stringify(selected,null,2)}</pre></details><div className="row"><button type="button" disabled={busy||entry.archived||!sameRef(selected,entry.expression)} onClick={()=>void run(async()=>onDraft(await rpc.management(sessionId,'startRevisionDraft',{ref:{asset_id:selected.asset_id,revision_id:selected.revision_id},version:entry.version})))}>{entry.origin==='local'?t("编辑新版本"):t("创建个人副本")}</button>{entry.origin!=='local'&&!sameRef(selected,entry.expression)&&<button type="button" disabled={busy} onClick={()=>void run(async()=>{chooseEntry(await rpc.management(sessionId,'selectRevision',{ref:{asset_id:selected.asset_id,revision_id:selected.revision_id},version:entry.version}));await refresh();})}>{t("设为当前版本")}</button>}<button type="button" disabled={busy} onClick={()=>void run(async()=>{chooseEntry(await rpc.management(sessionId,'setArchived',{asset_id:entry.expression.asset_id,version:entry.version,archived:!entry.archived}));await refresh();})}>{entry.archived?t("恢复到可用"):t("归档表情")}</button><button type="button" aria-pressed={refs.some(r=>sameRef(r,selected))} onClick={()=>setRefs(refs.some(r=>sameRef(r,selected))?refs.filter(r=>!sameRef(r,selected)):[...refs,{asset_id:selected.asset_id,revision_id:selected.revision_id}])}>{refs.some(r=>sameRef(r,selected))?t("取消导出选择"):t("选择此版本导出")}</button></div></section>}
 </aside></div><Conflict error={error}/>{(error as {current?:LibraryEntry})?.current&&<button type="button" onClick={()=>{chooseEntry((error as {current:LibraryEntry}).current);}}>{t("读取当前条目后继续")}</button>}</section>;
}
