import React,{useState} from 'react';
import type {ExpressionRef} from '../sample-catalog.js';
import type {DshRpc} from './contracts.js';
import {Conflict} from './ui.js';
export function PackControls({rpc,sessionId,refs,onImported}:{rpc:DshRpc;sessionId:string;refs:ExpressionRef[];onImported:()=>void}){
 const [file,setFile]=useState<File>(),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[status,setStatus]=useState(''),[unknown,setUnknown]=useState(false);
 const importFile=async()=>{if(!file)return;setBusy(true);setError(undefined);try{const r=await rpc.importPack(sessionId,file);setUnknown(false);setStatus(`导入完成：新增 ${r.added} 个版本，已有 ${r.existing} 个。已有条目的当前版本保持不变。`);onImported();}catch(e){setError(e);if((e as {code?:string}).code==='PACK_OUTCOME_UNKNOWN')setUnknown(true);}finally{setBusy(false);}};
 return <section className="stack amoji-pack-settings"><h3>完整表情包</h3><p>包中包含固定版本、语义、许可和素材，不包含个人设置或会话。</p><label>选择 .amoji 或 ZIP 文件<input aria-label="导入表情包" type="file" accept=".amoji,.zip,application/zip" disabled={busy||unknown} onChange={e=>{const next=e.target.files?.[0];if(next&&next.size>260*1024*1024){setError(new Error('完整包最多 260 MiB'));return;}setFile(next);setError(undefined);}}/></label>{file&&<p>{file.name}</p>}<div className="row"><button type="button" disabled={!file||busy} onClick={()=>void importFile()}>{unknown?'重试同一包并核对':'导入完整包'}</button>{unknown&&<button type="button" onClick={onImported}>刷新库核对结果</button>}</div><button type="button" disabled={!refs.length||busy} onClick={()=>{setBusy(true);setError(undefined);void rpc.exportPack(sessionId,refs,'我的表情').then(blob=>{if(!blob.size)throw new Error('导出内容为空');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='我的表情.amoji';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setStatus(`已下载 ${refs.length} 个所选版本。`);}).catch(setError).finally(()=>setBusy(false));}}>导出所选 {refs.length} 个版本</button><Conflict error={error}/><p role="status">{busy?'正在处理完整包…':status}</p></section>;
}
