import React from 'react';
import type { Expression } from '../sample-catalog.js';
import type { DshRpc } from './contracts.js';
import { AmojiImage } from './media.js';

export function CloseIcon() { return <svg aria-hidden="true" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="m6 6 12 12M18 6 6 18"/></svg>; }
export function SmileIcon() { return <svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><circle cx="12" cy="12" r="9"/><path d="M8 14s1 3 4 3 4-3 4-3"/><path d="M8 8v2m8-2v2"/></svg>; }
export function ExpressionTile({rpc,sessionId,expression,selected,disabled,onSelect}:{rpc:DshRpc;sessionId:string;expression:Expression;selected:boolean;disabled?:boolean;onSelect:()=>void}) {
 return <button type="button" className="amoji-expression-tile" aria-label={expression.name} aria-pressed={selected} title={expression.semantics.meaning} disabled={disabled} onClick={onSelect}><AmojiImage rpc={rpc} sessionId={sessionId} refValue={expression} thumbnail/><span className="amoji-expression-label">{expression.name}</span></button>;
}

export const styles = `
.amoji{font-family:inherit;font-size:14px;color:var(--amoji-ink);line-height:1.5;--amoji-bg:#fff;--amoji-ink:#202329;--amoji-muted:#666d78;--amoji-line:#e4e7ec;--amoji-wash:#f3f5f8;--amoji-accent:#4468dc;--amoji-selected:#edf1ff;--amoji-radius:10px}
[data-ds-dark-theme] .amoji,.amoji[data-ds-dark-theme]{--amoji-bg:#24262c;--amoji-ink:#eff0f3;--amoji-muted:#aeb4bf;--amoji-line:#40434c;--amoji-wash:#2d3037;--amoji-accent:#a4b8ff;--amoji-selected:#343f61}
.amoji [hidden]{display:none!important}.amoji *{box-sizing:border-box}
.amoji button,.amoji input,.amoji textarea,.amoji select{font:inherit;color:inherit;border:1px solid var(--amoji-line);border-radius:8px;background:var(--amoji-bg);padding:8px 12px;max-width:100%;min-height:36px}
.amoji button{cursor:pointer;transition:background .12s,border-color .12s}.amoji button:hover:not(:disabled){background:var(--amoji-wash)}.amoji button:disabled{opacity:.46;cursor:default}
.amoji button[aria-pressed=true]{background:var(--amoji-selected);border-color:var(--amoji-accent)}
.amoji button.primary{background:#4468dc;color:#fff;border-color:transparent;font-weight:600}.amoji button.primary:hover:not(:disabled){background:#3658c4}
.amoji :focus-visible{outline:2px solid var(--amoji-accent);outline-offset:3px}.amoji label{display:grid;gap:6px}.amoji textarea{min-height:76px;resize:vertical}.amoji input:not([type=checkbox]),.amoji textarea{width:100%}.amoji input::placeholder,.amoji textarea::placeholder{color:var(--amoji-muted)}
.amoji h2{font-size:18px;font-weight:600;letter-spacing:-.2px;margin:0}.amoji h3{font-size:15px;font-weight:600;margin:0}.amoji p{margin:0}.amoji small,.amoji .muted{color:var(--amoji-muted);font-size:12px}.amoji pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.amoji summary{cursor:pointer;color:var(--amoji-muted);font-size:12px;padding:4px 0}.amoji details[open]>summary{margin-bottom:8px}.amoji .row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.amoji .stack{display:grid;gap:16px}.amoji .quiet{border-color:transparent;background:transparent;color:var(--amoji-muted);padding:6px 8px}.amoji .icon-button{width:40px;height:40px;display:grid;place-items:center;padding:0;border:0;background:transparent;flex:none}
.amoji .amoji-trigger{display:flex;align-items:center;gap:6px;border-color:transparent;background:transparent;padding:6px 8px;color:inherit}.amoji .amoji-trigger[aria-expanded=true]{background:var(--amoji-selected);color:var(--amoji-accent)}
.amoji-picker{display:flex;flex-direction:column;border:1px solid var(--amoji-line);border-radius:16px;background:var(--amoji-bg);color:var(--amoji-ink);padding:0;box-shadow:0 12px 44px #0003;min-height:0}
.amoji-picker-head{display:flex;align-items:center;justify-content:space-between;gap:8px;flex:none;padding:8px 10px 0 18px}.amoji-picker-head h2{font-size:15px}
.amoji-picker-search{display:flex;align-items:center;gap:6px;padding:10px 16px 12px;flex:none}.amoji-picker-search input{min-width:0;background:var(--amoji-wash);border-color:transparent}.amoji-picker-search button{flex:none}
.amoji-picker-body{overflow-y:auto;overscroll-behavior:contain;min-height:64px;flex:1;padding:0 12px 12px;scrollbar-width:thin}
.amoji-expression-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px}
.amoji button.amoji-expression-tile{border:1px solid transparent;border-radius:10px;background:transparent;display:flex;flex-direction:column;align-items:center;gap:5px;padding:8px 4px;min-width:0;min-height:114px;color:var(--amoji-ink)}
.amoji button.amoji-expression-tile[aria-pressed=true]{background:var(--amoji-selected);border-color:var(--amoji-accent)}
.amoji-expression-label{font-size:12px;line-height:18px;font-weight:500;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.amoji .amoji-media{display:flex;position:relative;flex-direction:column;align-items:center;justify-content:center;gap:6px;margin:0;width:152px;min-height:152px;max-width:100%}.amoji .amoji-media img{display:block;width:152px;height:152px;max-width:100%;object-fit:contain}
.amoji .amoji-thumbnail{width:76px;height:76px;min-height:76px}.amoji .amoji-thumbnail img{width:76px;height:76px}
.amoji-media-loading{display:block;width:72%;aspect-ratio:1;border-radius:24px;background:var(--amoji-wash)}
.amoji-media-fallback{font-size:13px;padding:12px;background:var(--amoji-wash);border-radius:10px;overflow-wrap:anywhere;text-align:center}.amoji-media-fallback small{display:block;margin-top:4px}
.amoji button.amoji-playback{padding:2px 8px;min-height:28px;font-size:11px;border-color:transparent;background:transparent;color:var(--amoji-muted)}
.amoji-picker-footer{border-top:1px solid var(--amoji-line);padding:12px 16px;flex:none;max-height:46%;overflow:hidden;display:flex;flex-direction:column}.amoji-selection{min-height:0;overflow:auto}.amoji-selection>p{color:var(--amoji-muted);font-size:13px;line-height:1.5;margin-top:4px}.amoji-selection>details{margin-top:4px}.amoji-selection small{overflow-wrap:anywhere}.amoji-send-row{flex:none;display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:10px}.amoji-notice{font-size:12px;line-height:1.5;margin-top:8px!important;color:var(--amoji-muted)}.amoji-empty{padding:32px 16px;color:var(--amoji-muted);text-align:center;font-size:13px}
.amoji.amoji-message{display:flex;flex-direction:column;align-items:flex-start;gap:4px;margin:12px 0 18px}.amoji.amoji-message-human{align-items:flex-end}.amoji-message-detail{max-width:340px}.amoji-message-detail summary{text-align:right;font-size:11px}.amoji-message-detail[open]{border:1px solid var(--amoji-line);background:var(--amoji-bg);border-radius:10px;padding:8px 12px}.amoji-message-detail p{margin:6px 0;color:var(--amoji-muted);font-size:13px}.amoji-message-detail small{overflow-wrap:anywhere}
.amoji .draft-list{align-self:start;align-content:start;grid-auto-rows:max-content}.amoji .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(112px,1fr));gap:8px}.amoji .tile{display:flex;flex-direction:column;align-items:center;min-width:0;padding:8px;border-radius:10px}.amoji .tile>button{width:100%;overflow-wrap:anywhere}.amoji .split{display:grid;grid-template-columns:minmax(180px,.65fr) minmax(290px,1.6fr);gap:24px}.amoji .preview{display:grid;gap:12px;background:var(--amoji-wash);border-radius:12px;padding:20px}.amoji .preview img{width:160px;height:160px;object-fit:contain;border-radius:10px}.amoji .error{border-left:3px solid #d06b67;padding:10px 12px;background:var(--amoji-wash);font-size:13px}.amoji-dialog{width:min(1000px,calc(100vw - 32px));height:min(780px,calc(100dvh - 48px));max-height:calc(100dvh - 32px);margin:auto;padding:24px;background:var(--amoji-bg);color:var(--amoji-ink);border:1px solid var(--amoji-line);border-radius:16px;overflow:auto}.amoji-dialog::backdrop{background:#0007;backdrop-filter:blur(3px)}.amoji .toolbar{position:sticky;top:-24px;background:var(--amoji-bg);padding:12px 0;z-index:1;justify-content:space-between;border-bottom:1px solid var(--amoji-line);margin-bottom:20px}.amoji .tabs{margin-bottom:20px}.amoji [role=status]:empty{display:none}.amoji .fields{display:grid;grid-template-columns:1fr 1fr;gap:16px}.amoji .wide{grid-column:1/-1}
@media(max-width:650px){.amoji .split,.amoji .fields{grid-template-columns:1fr}.amoji-dialog{padding:16px;width:calc(100vw - 16px);height:calc(100dvh - 24px)}.amoji .toolbar{top:-16px}.amoji .grid{grid-template-columns:repeat(auto-fill,minmax(95px,1fr))}.amoji-expression-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(prefers-reduced-motion:reduce){.amoji button{transition:none}}
`;
export function Styles(){return <style>{styles}</style>;}
export function Conflict({error,onRefresh}:{error:unknown;onRefresh?:()=>void}) {if (!error) return null;const e=error as {message?:string;current?:unknown};return <div role="alert" className="error"><p>{e.message||'操作失败，请重试'}</p>{e.current!==undefined&&<><p>当前内容已变化，本次输入已保留。</p><details><summary>查看服务中的当前内容</summary><pre>{JSON.stringify(e.current,null,2)}</pre></details></>}{onRefresh&&<button type="button" onClick={onRefresh}>核对当前状态</button>}</div>;}
